version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: proveni-postgres
    restart: always

    environment:
      POSTGRES_USER: proveni
      POSTGRES_PASSWORD: proveni123
      POSTGRES_DB: proveni_db

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
